"use strict";
(()=>{
 const $=id=>document.getElementById(id),canvas=$("stage"),ctx=canvas.getContext("2d",{alpha:true});
 const ids=["headX","headY","roll","bodyX","bodyZ","breath","eyeL","eyeR","gazeX","gazeY","browL","browR","mouthOpen","mouthForm","mouthX","hairPhysics","ribbonPhysics","clothesPhysics"],c=Object.fromEntries(ids.map(id=>[id,$(id)]));
 const state={last:performance.now(),stream:null,expression:"neutral",hairL:0,hairLV:0,hairR:0,hairRV:0,ribbonL:0,ribbonLV:0,ribbonR:0,ribbonRV:0,bow:0,bowV:0,skirt:0,skirtV:0,sleeveL:0,sleeveLV:0,sleeveR:0,sleeveRV:0};
 const P={hair:"#24202a",hair2:"#17141d",hairHi:"#3a3243",skin:"#f3d7d6",skinShade:"#e7c5c7",ink:"#312a35",eye:"#9a6fc5",eyeDark:"#3b2949",white:"#fff9fc",lace:"#f2e9f0",dress:"#18151d",dress2:"#27212d",accent:"#bb6fa8",blush:"#f188a8",mouth:"#9b5368",mouthDark:"#5b2635",shoe:"#16131a"};
 const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),v=k=>Number(c[k]?.value)||0;
 function outputs(){for(const id of ids){const o=$(id+"Out");if(!o)continue;o.textContent=["breath","eyeL","eyeR","mouthOpen","hairPhysics","ribbonPhysics","clothesPhysics"].includes(id)?`${Math.round(v(id))}%`:Math.round(v(id))}}
 function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,2),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}}
 function ellipse(x,y,rx,ry,fill,rot=0){ctx.beginPath();ctx.ellipse(x,y,rx,ry,rot,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill()}
 function path(fill,draw,stroke=null,width=1){ctx.beginPath();draw(ctx);ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke()}}
 function ribbonShape(x,y,s,rot,flip=1,fill=P.dress2){ctx.save();ctx.translate(x,y);ctx.rotate(rot);path(fill,p=>{p.moveTo(0,0);p.bezierCurveTo(22*s*flip,-17*s,52*s*flip,-18*s,63*s*flip,-6*s);p.bezierCurveTo(53*s*flip,8*s,34*s*flip,26*s,5*s*flip,21*s);p.lineTo(0,0)});ctx.restore()}
 function drawBackground(cx,cy,s){const g=ctx.createRadialGradient(cx,cy-120*s,20*s,cx,cy,430*s);g.addColorStop(0,"rgba(177,105,165,.16)");g.addColorStop(.55,"rgba(92,72,118,.08)");g.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height);ellipse(cx,cy+620*s,190*s,28*s,"rgba(0,0,0,.34)")}
 function drawLegs(cx,cy,s,bodyShift,bodyRot){ctx.save();ctx.translate(cx+bodyShift,cy+333*s);ctx.rotate(bodyRot);const gap=31*s;for(const side of[-1,1]){ctx.save();ctx.translate(side*gap,0);ctx.fillStyle=P.skinShade;ctx.fillRect(-15*s,0,30*s,210*s);ctx.fillStyle="#fbf7fb";ctx.fillRect(-18*s,82*s,36*s,82*s);ctx.fillStyle=P.dress2;ctx.fillRect(-18*s,78*s,36*s,13*s);ellipse(0,207*s,31*s,20*s,P.shoe);path(P.shoe,p=>{p.moveTo(-28*s,195*s);p.lineTo(27*s,195*s);p.lineTo(39*s,214*s);p.lineTo(-33*s,214*s)});ctx.restore()}ctx.restore()}
 function drawBackBow(cx,cy,s,bodyShift,bodyRot){ctx.save();ctx.translate(cx+bodyShift,cy+182*s);ctx.rotate(bodyRot+state.bow*Math.PI/180);ribbonShape(0,0,s,0,-1,P.accent);ribbonShape(0,0,s,0,1,P.accent);ellipse(0,0,22*s,18*s,P.dress2);for(const side of[-1,1])path(P.accent,p=>{p.moveTo(side*7*s,11*s);p.lineTo(side*42*s,138*s);p.lineTo(side*4*s,109*s)});ctx.restore()}
 function drawTorso(cx,cy,s,bodyShift,bodyRot,breath){ctx.save();ctx.translate(cx+bodyShift,cy+174*s);ctx.rotate(bodyRot);ctx.scale(breath,1);path(P.dress,p=>{p.moveTo(-72*s,-68*s);p.bezierCurveTo(-103*s,-34*s,-104*s,80*s,-83*s,125*s);p.lineTo(83*s,125*s);p.bezierCurveTo(104*s,80*s,103*s,-34*s,72*s,-68*s);p.bezierCurveTo(37*s,-86*s,-37*s,-86*s,-72*s,-68*s)});path(P.white,p=>{p.moveTo(-42*s,-70*s);p.lineTo(-24*s,105*s);p.lineTo(24*s,105*s);p.lineTo(42*s,-70*s);p.bezierCurveTo(17*s,-82*s,-17*s,-82*s,-42*s,-70*s)});ellipse(0,-47*s,18*s,10*s,P.dress2);for(const side of[-1,1])path(P.lace,p=>{p.moveTo(side*10*s,-55*s);p.bezierCurveTo(side*34*s,-46*s,side*49*s,-24*s,side*51*s,-2*s);p.lineTo(side*28*s,4*s);p.bezierCurveTo(side*24*s,-19*s,side*17*s,-38*s,side*10*s,-55*s)});ctx.fillStyle=P.accent;ctx.fillRect(-89*s,35*s,178*s,15*s);ctx.fillStyle=P.dress2;ctx.fillRect(-92*s,50*s,184*s,9*s);ctx.restore()}
 function drawSkirt(cx,cy,s,bodyShift,bodyRot){ctx.save();ctx.translate(cx+bodyShift,cy+286*s);ctx.rotate(bodyRot+state.skirt*.002);path(P.dress,p=>{p.moveTo(-84*s,-4*s);p.bezierCurveTo(-126*s,55*s-state.skirt*s*.08,-153*s,170*s,-143*s,235*s);p.quadraticCurveTo(0,271*s,143*s,235*s);p.bezierCurveTo(153*s,170*s,126*s,55*s+state.skirt*s*.08,84*s,-4*s)});path(P.white,p=>{p.moveTo(-59*s,2*s);p.bezierCurveTo(-77*s,72*s,-87*s,176*s,-74*s,221*s);p.quadraticCurveTo(0,242*s,74*s,221*s);p.bezierCurveTo(87*s,176*s,77*s,72*s,59*s,2*s)});for(let i=-4;i<=4;i++)ellipse(i*31*s,235*s+(Math.abs(i)%2)*4*s,24*s,12*s,P.lace);ctx.strokeStyle=P.dress2;ctx.lineWidth=3*s;for(const side of[-1,1]){ctx.beginPath();ctx.moveTo(side*32*s,16*s);ctx.quadraticCurveTo(side*58*s,114*s,side*48*s,219*s);ctx.stroke()}ctx.restore()}
 function drawArms(cx,cy,s,bodyShift,bodyRot){for(const side of[-1,1]){const phys=side<0?state.sleeveL:state.sleeveR;ctx.save();ctx.translate(cx+bodyShift+side*84*s,cy+150*s);ctx.rotate(bodyRot+side*.15+phys*Math.PI/180*.18);path(P.dress,p=>{p.moveTo(-15*s,-30*s);p.bezierCurveTo(side*28*s,-24*s,side*43*s,53*s,side*32*s,113*s);p.lineTo(side*4*s,109*s);p.bezierCurveTo(side*3*s,41*s,-15*s,-8*s,-15*s,-30*s)});path(P.white,p=>{p.moveTo(side*9*s,62*s);p.lineTo(side*34*s,62*s);p.lineTo(side*30*s,100*s);p.lineTo(side*3*s,100*s)});ellipse(side*27*s,126*s,18*s,24*s,P.skin,side*.08);for(let i=0;i<4;i++)ellipse(side*(10+i*8)*s,103*s,8*s,6*s,P.lace);ctx.restore()}}
 function drawNeck(cx,cy,s,headShiftX,headShiftY,bodyShift){ctx.save();ctx.translate(cx+bodyShift*.3+headShiftX,cy+95*s+headShiftY);ctx.fillStyle=P.skinShade;ctx.fillRect(-19*s,0,38*s,64*s);ellipse(0,52*s,28*s,14*s,P.skinShade);ctx.restore()}
 function drawBackHair(cx,cy,s,hx,hy,roll,bodyShift){ctx.save();ctx.translate(cx+bodyShift*.25+hx,cy+hy);ctx.rotate(roll);ellipse(0,4*s,123*s,145*s,P.hair2);for(const side of[-1,1]){const a=(side<0?state.hairL:state.hairR)*Math.PI/180;ctx.save();ctx.translate(side*89*s,35*s);ctx.rotate(side*.08+a);path(P.hair2,p=>{p.moveTo(-28*s,-56*s);p.bezierCurveTo(side*23*s,28*s,side*35*s,156*s,side*10*s,225*s);p.bezierCurveTo(side*-20*s,175*s,-50*s,72*s,-28*s,-56*s)});ctx.restore()}ctx.restore()}
 function drawFace(cx,cy,s,hx,hy,roll,bodyShift,now){ctx.save();ctx.translate(cx+bodyShift*.25+hx,cy+hy);ctx.rotate(roll);const perspective=1-Math.abs(v("headX"))*.0018;ctx.scale(perspective,1);ellipse(0,5*s,91*s,107*s,P.skin);ellipse(-53*s,31*s,23*s,10*s,state.expression==="shy"?"rgba(241,136,168,.42)":"rgba(241,136,168,.13)");ellipse(53*s,31*s,23*s,10*s,state.expression==="shy"?"rgba(241,136,168,.42)":"rgba(241,136,168,.13)");const gazeX=v("gazeX")*.065*s,gazeY=v("gazeY")*.04*s,blink=Math.min(1,Math.abs(((now/3650)%1)-.93)/.025),autoBlink=clamp(blink,0,1);for(const side of[-1,1]){let open=clamp(v(side<0?"eyeL":"eyeR")/100,0,1);if(open>.92)open*=autoBlink;const x=side*36*s,y=-4*s,ry=(1.5+12*open)*s;ellipse(x,y,25*s,ry,P.white);if(open>.05){ellipse(x+gazeX,y+2*s+gazeY,10*s,Math.max(2,9*open)*s,P.eye);ellipse(x+gazeX,y+3*s+gazeY,5*s,Math.max(1.5,5*open)*s,P.eyeDark);ellipse(x+gazeX-2*s,y-1*s+gazeY,2.2*s,Math.max(1,2.8*open)*s,"#fff")}ctx.strokeStyle=P.ink;ctx.lineWidth=3*s;ctx.beginPath();ctx.moveTo(x-25*s,y);ctx.quadraticCurveTo(x,y-(13+4*open)*s,x+25*s,y);ctx.stroke();const brow=v(side<0?"browL":"browR")*.09*s;ctx.beginPath();ctx.moveTo(x-22*s,-33*s-brow);ctx.quadraticCurveTo(x,-40*s-brow,x+22*s,-33*s+brow*.22);ctx.stroke()}const mo=clamp(v("mouthOpen")/100,0,1),form=v("mouthForm")/100,mx=v("mouthX")*.08*s,mw=(17+13*Math.abs(form))*s,mh=(2.2+20*mo)*s;ellipse(mx,50*s,mw,mh,mo>.07?P.mouthDark:P.mouth);if(mo>.35)ellipse(mx,55*s,mw*.55,mh*.32,"#dc8099");ctx.restore()}
 function drawFrontHair(cx,cy,s,hx,hy,roll,bodyShift){ctx.save();ctx.translate(cx+bodyShift*.25+hx,cy+hy);ctx.rotate(roll);ctx.fillStyle=P.hair;ctx.beginPath();ctx.arc(0,-18*s,103*s,Math.PI*.93,Math.PI*2.07);ctx.lineTo(96*s,34*s);ctx.quadraticCurveTo(55*s,-4*s,31*s,30*s);ctx.quadraticCurveTo(11*s,-13*s,-9*s,27*s);ctx.quadraticCurveTo(-32*s,-12*s,-96*s,36*s);ctx.closePath();ctx.fill();for(let i=-3;i<=3;i++){ctx.fillStyle=i%2?P.hair2:P.hair;ctx.beginPath();ctx.moveTo(i*24*s-18*s,-91*s);ctx.quadraticCurveTo(i*18*s,-28*s+(i%2?state.hairL:state.hairR)*.15*s,i*13*s,43*s);ctx.lineTo((i+1)*15*s,18*s);ctx.quadraticCurveTo((i+1)*24*s,-56*s,(i+1)*22*s,-92*s);ctx.closePath();ctx.fill()}ctx.globalAlpha=.18;path(P.hairHi,p=>{p.moveTo(-54*s,-82*s);p.quadraticCurveTo(-12*s,-105*s,43*s,-78*s);p.lineTo(27*s,-68*s);p.quadraticCurveTo(-12*s,-88*s,-46*s,-70*s)});ctx.globalAlpha=1;ctx.restore()}
 function drawHeaddress(cx,cy,s,hx,hy,roll,bodyShift){ctx.save();ctx.translate(cx+bodyShift*.25+hx,cy+hy-104*s);ctx.rotate(roll);ctx.fillStyle=P.dress2;ctx.fillRect(-68*s,1*s,136*s,14*s);for(let i=-4;i<=4;i++)ellipse(i*18*s,0,15*s,20*s,P.lace);for(const side of[-1,1]){ctx.save();ctx.translate(side*91*s,38*s);ctx.rotate(side*(.15+(side<0?state.ribbonL:state.ribbonR)*Math.PI/180));ribbonShape(0,0,s,0,side,P.accent);ribbonShape(0,0,s,0,-side,P.accent);ellipse(0,0,11*s,10*s,P.lace);ctx.restore()}ctx.restore()}
 function physics(dt){const driver=-(v("headX")*.2+v("roll")*.55+v("bodyZ")*.25+v("bodyX")*.12),step=(target,key,vel,spring,damp)=>{state[vel]+=(target-state[key])*spring*dt;state[vel]*=Math.pow(damp,dt*60);state[key]+=state[vel]*dt*60};const hp=v("hairPhysics")/100,rp=v("ribbonPhysics")/100,cp=v("clothesPhysics")/100;step(driver*hp,"hairL","hairLV",11,.79);step(driver*.82*hp,"hairR","hairRV",10,.8);step(-driver*.76*rp,"ribbonL","ribbonLV",8.7,.82);step(-driver*.62*rp,"ribbonR","ribbonRV",8.2,.83);step(driver*.55*rp,"bow","bowV",7.5,.84);step(driver*.16*cp,"skirt","skirtV",7.2,.86);step(driver*.22*cp,"sleeveL","sleeveLV",8,.85);step(driver*.19*cp,"sleeveR","sleeveRV",8,.85)}
 function draw(now){resize();ctx.clearRect(0,0,canvas.width,canvas.height);const s=Math.min(canvas.width/720,canvas.height/1020),cx=canvas.width/2,cy=canvas.height/2-278*s,idle=Math.sin(now/2100)*1.5*s,bodyShift=v("bodyX")*2.2*s+idle,bodyRot=v("bodyZ")*Math.PI/180*.75,breath=1+Math.sin(now/670)*v("breath")*.00075,hx=v("headX")*1.45*s,hy=v("headY")*.86*s+Math.sin(now/1800)*1.2*s,roll=v("roll")*Math.PI/180+bodyRot*.18;drawBackground(cx,cy,s);drawLegs(cx,cy,s,bodyShift,bodyRot);drawBackBow(cx,cy,s,bodyShift,bodyRot);drawBackHair(cx,cy,s,hx,hy,roll,bodyShift);drawSkirt(cx,cy,s,bodyShift,bodyRot);drawArms(cx,cy,s,bodyShift,bodyRot);drawTorso(cx,cy,s,bodyShift,bodyRot,breath);drawNeck(cx,cy,s,hx,hy,bodyShift);drawFace(cx,cy,s,hx,hy,roll,bodyShift,now);drawFrontHair(cx,cy,s,hx,hy,roll,bodyShift);drawHeaddress(cx,cy,s,hx,hy,roll,bodyShift)}
 function tick(now){const dt=Math.min(.05,(now-state.last)/1000);state.last=now;physics(dt);draw(now);requestAnimationFrame(tick)}
 const presets={neutral:{eyeL:100,eyeR:100,browL:0,browR:0,mouthOpen:0,mouthForm:0,mouthX:0},smile:{eyeL:94,eyeR:94,browL:12,browR:12,mouthOpen:14,mouthForm:72,mouthX:0},happy:{eyeL:68,eyeR:68,browL:28,browR:28,mouthOpen:34,mouthForm:92,mouthX:0},laugh:{eyeL:12,eyeR:12,browL:22,browR:22,mouthOpen:82,mouthForm:100,mouthX:0},sad:{eyeL:76,eyeR:76,browL:-46,browR:-46,mouthOpen:8,mouthForm:-62,mouthX:0},angry:{eyeL:83,eyeR:83,browL:-72,browR:-72,mouthOpen:20,mouthForm:-48,mouthX:0},surprised:{eyeL:100,eyeR:100,browL:68,browR:68,mouthOpen:86,mouthForm:0,mouthX:0},shy:{eyeL:62,eyeR:62,browL:20,browR:20,mouthOpen:9,mouthForm:50,mouthX:8}};
 function expression(name){state.expression=name;Object.entries(presets[name]||presets.neutral).forEach(([k,n])=>{if(c[k])c[k].value=n});outputs();$("status").textContent=`Expression: ${name}`}
 document.querySelectorAll("[data-expression]").forEach(b=>b.addEventListener("click",()=>expression(b.dataset.expression)));ids.forEach(id=>c[id]?.addEventListener("input",outputs));
 $("resetModel").addEventListener("click",()=>{const defaults={headX:0,headY:0,roll:0,bodyX:0,bodyZ:0,breath:50,gazeX:0,gazeY:0,mouthX:0,hairPhysics:70,ribbonPhysics:65,clothesPhysics:52};Object.entries(defaults).forEach(([k,n])=>{if(c[k])c[k].value=n});for(const k of Object.keys(state))if(/^(hair|ribbon|bow|skirt|sleeve)/.test(k)&&typeof state[k]==="number")state[k]=0;expression("neutral");$("status").textContent="Megu Maid reset"});
 async function startCam(){if(state.stream)return;try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:640},height:{ideal:480}},audio:false});$("camera").srcObject=state.stream;await $("camera").play();$("startCamera").disabled=true;$("stopCamera").disabled=false;$("cameraStatus").textContent="Camera active locally; no frames are uploaded."}catch(e){$("cameraStatus").textContent=e?.name==="NotAllowedError"?"Camera permission denied.":"Could not start camera."}}
 function stopCam(){state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;$("camera").srcObject=null;$("startCamera").disabled=false;$("stopCamera").disabled=true;$("cameraStatus").textContent="Camera off."}
 $("startCamera").addEventListener("click",startCam);$("stopCamera").addEventListener("click",stopCam);window.addEventListener("beforeunload",stopCam);outputs();expression("neutral");requestAnimationFrame(tick)
})();