"use strict";
(() => {
  const $ = id => document.getElementById(id);
  const video=$("cameraPreview"),start=$("startCamera"),stop=$("stopCamera"),calibrate=$("calibrateTracking"),status=$("trackingStatus"),smooth=$("trackingSmoothing"),smoothOut=$("trackingSmoothingOut");
  const headX=$("headX"),headY=$("headY"),bodyZ=$("bodyZ"),eyeOpen=$("eyeOpen"),mouthOpen=$("mouthOpen");
  let stream=null,detector=null,running=false,raf=0,neutral=null,sx=0,sy=0,sz=0,seye=1,smouth=0,busy=false;
  const supported=Boolean(navigator.mediaDevices?.getUserMedia && "FaceDetector" in window);
  const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
  const mean=pts=>pts.length?pts.reduce((a,p)=>({x:a.x+p.x,y:a.y+p.y}),{x:0,y:0})&&(()=>{const s=pts.reduce((a,p)=>({x:a.x+p.x,y:a.y+p.y}),{x:0,y:0});return{x:s.x/pts.length,y:s.y/pts.length}})():null;
  function setStatus(t){if(status)status.textContent=t}
  function dispatch(c,v){if(!c)return;c.value=String(v);c.dispatchEvent(new Event("input",{bubbles:true}))}
  function smoothTo(c,t,a){return c+(t-c)*a}
  function landmarkGroups(face){const out={eyes:[],mouth:[]};for(const lm of face.landmarks||[]){const pts=(lm.locations||[]).map(p=>({x:p.x,y:p.y}));if(!pts.length)continue;const type=String(lm.type||"").toLowerCase();if(type.includes("eye"))out.eyes.push({pts,center:mean(pts)});else if(type.includes("mouth"))out.mouth.push(...pts)}return out}
  function estimate(face){const box=face.boundingBox,cx=(box.x+box.width/2)/video.videoWidth,cy=(box.y+box.height/2)/video.videoHeight,groups=landmarkGroups(face);if(!neutral)neutral={x:cx,y:cy,roll:0};let roll=0,eye=1,mouth=0,used=[];
    if(groups.eyes.length>=2){const e=[...groups.eyes].sort((a,b)=>a.center.x-b.center.x);roll=Math.atan2(e.at(-1).center.y-e[0].center.y,e.at(-1).center.x-e[0].center.x)*180/Math.PI;used.push("roll");const spans=e.map(g=>{const ys=g.pts.map(p=>p.y);return (Math.max(...ys)-Math.min(...ys))/Math.max(1,box.height)});if(spans.some(v=>v>0)){eye=clamp((spans.reduce((a,b)=>a+b,0)/spans.length)/.055,0,1);used.push("blink")}}
    if(groups.mouth.length>=2){const ys=groups.mouth.map(p=>p.y),span=(Math.max(...ys)-Math.min(...ys))/Math.max(1,box.height);mouth=clamp((span-.015)/.11,0,1);used.push("mouth")}
    return{x:clamp((cx-neutral.x)*-120,-30,30),y:clamp((cy-neutral.y)*120,-30,30),z:clamp(roll-(neutral.roll||0),-20,20),eye,mouth,used}}
  async function detect(){if(!running)return;if(!busy&&video?.readyState>=2&&detector){busy=true;try{const faces=await detector.detect(video);if(faces.length){const m=estimate(faces[0]),a=clamp(1-(Number(smooth?.value||70)/100)*.85,.04,.6);sx=smoothTo(sx,m.x,a);sy=smoothTo(sy,m.y,a);sz=smoothTo(sz,m.z,a);seye=smoothTo(seye,m.eye,a);smouth=smoothTo(smouth,m.mouth,a);dispatch(headX,sx.toFixed(2));dispatch(headY,sy.toFixed(2));if(m.used.includes("roll"))dispatch(bodyZ,sz.toFixed(2));if(m.used.includes("blink"))dispatch(eyeOpen,Math.round(seye*100));if(m.used.includes("mouth"))dispatch(mouthOpen,Math.round(smouth*100));setStatus(m.used.length?`Tracking locally • landmark assist: ${m.used.join(", ")}`:"Tracking locally • position-only fallback")}else setStatus("Camera active — face not detected")}catch{setStatus("Tracking paused — detector error")}finally{busy=false}}raf=requestAnimationFrame(detect)}
  async function startCamera(){if(running)return;if(!navigator.mediaDevices?.getUserMedia){setStatus("Camera API unavailable in this browser");return}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:640},height:{ideal:480}},audio:false});video.srcObject=stream;await video.play();if(supported){detector=new FaceDetector({fastMode:true,maxDetectedFaces:1});setStatus("Camera active — local face detection ready")}else{detector=null;setStatus("Camera active. Native face tracking is unsupported here; manual sliders remain available.")}running=true;stop.disabled=false;calibrate.disabled=!supported;start.disabled=true;neutral=null;sx=sy=sz=0;seye=1;smouth=0;raf=requestAnimationFrame(detect)}catch(e){setStatus(e?.name==="NotAllowedError"?"Camera permission was denied":"Could not start camera")}}
  function stopCamera(){running=false;cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop());stream=null;detector=null;if(video)video.srcObject=null;start.disabled=false;stop.disabled=true;calibrate.disabled=true;neutral=null;setStatus("Camera off")}
  start?.addEventListener("click",startCamera);stop?.addEventListener("click",stopCamera);calibrate?.addEventListener("click",()=>{neutral=null;setStatus("Recalibrating neutral head position…")});smooth?.addEventListener("input",()=>{if(smoothOut)smoothOut.textContent=`${smooth.value}%`});window.addEventListener("beforeunload",stopCamera);if(!supported&&status)status.textContent="Native face tracking support will be checked when camera starts.";window.MeguTracker={start:startCamera,stop:stopCamera,supported:()=>supported};
})();